stages:
  - test

language: node_js
node_js:
  - stable
os: linux
dist: xenial

jobs:
  include:
    - stage: test
      name: Test

      script:
        - npm run prettier
        - npm run lint
        - npm test
    - stage: coverage
      if: branch = main
      name: Coverage

      before_install:
        - npm install -g codecov

      script:
        - npm run test:coverage_report
