stages:
  - test

language: node_js
node_js:
  - stable
os: linux
dist: xenial

jobs:
  include:
    - stage: test
      name: Test

      script:
        - npm run prettier
        - npm run lint
        - npm test
